from .user import User
from .student_year import StudentYear
from .role import Role
from .user_status import UserStatus
from .module import Module
from .subject import Subject
from .topic import Topic
from .question import Question
from .answer import Answer
from .comment import Comment
from .consultation import Consultation
from .consultation_student import *
from .image import Image
from .proffessor_subject import *
from .grade import Grade
from .answer_grade import *