STUDENT_YEAR1 = 1
STUDENT_YEAR2 = 2
STUDENT_YEAR3 = 3
STUDENT_YEAR4 = 4

ROLE_STUDENT = 1
ROLE_PROFESSOR = 2
ROLE_ADMIN = 3

USER_STATUS_EMAIL_UNCONFIRMED = 1
USER_STATUS_NOT_APPROVED = 2
USER_STATUS_APPROVED = 3
USER_STATUS_SUSPENDED = 4
